import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";

const REGION = 'us-west-2';
const TABLE_NAME = 'comic_series_to_exclude';

const client = new DynamoDB({ region: REGION });
const ddb = DynamoDBDocument.from(client, {
    marshallOptions: { removeUndefinedValues: true }
});

const SERIES_TO_BACKFILL = [
    "The Batman & Scooby-Doo Mysteries",
    "Harley Quinn: The Animated Series - The Eat, Bang, Kill Tour",
    "BRZRKR",
    "Getting Dizzy",
    "We Have Demons",
    "Batgirls",
    "Black Manta",
    "Teen Titans Academy",
    "Titans United",
    "Wonder Girl",
    "Wonder Woman",
    "Apex Legends: Overtime",
    "Army of Darkness 1979",
    "Army of Darkness",
    "Elvira Meets Vincent Price",
    "KISS: Phantom Obsession",
    "Red Sonja: Black, White, Red",
    "Sheena: Queen of the Jungle",
    "G.I. Joe: A Real American Hero",
    "Jupiter's Legacy: Requiem",
    "King Spawn",
    "Defenders",
    "Excalibur",
    "Hulk",
    "Ka-Zar: Lord of the Savage Land",
    "Miles Morales: Spider-Man",
    "Savage Avengers",
    "The Thing",
    "X-Force",
    "Rick And Morty: Corporate Assets",
    "Mega",
    "Catwoman",
    "Nightwing",
    "Scooby-Doo, Where Are You?",
    "Barbarella",
    "Black Panther",
    "Venom",
    "Exciting Comics",
    "Gold Digger",
    "Power Rangers",
    "Power Rangers Universe",
    "Action Comics",
    "Justice League",
    "The Flash",
    "Magic: The Gathering",
    "Crush & Lobo",
    "Suicide Squad",
    "Captain Marvel",
    "Shang-Chi",
    "Thor",
    "Mighty Morphin",
    "Vampiverse",
    "Savage Dragon",
    "Fantastic Four",
    "Green Lantern",
    "Looney Tunes",
    "She-Hulk",
    "Young Animal",
    "Ant",
    "Ant-Man",
    "Gambit",
    "Iron Fist",
    "Marvel Previews",
    "Mad",
    "Ninja High School",
    "Mighty Morphin Power Rangers",
    "Cinebook",
    "Ediciones La Cupula",
    "Wolverine",
    "Killadelphia",
    "Jungle Comics",
    "Planet Comics",
    "House of Slaughter",
    "Batman Incorporated",
    "Gargoyles",
    "Ghost Rider",
    "X-Men: Red",
    "My Little Pony",
    "Immortal X-Men",
    "Manga Z",
    "Rick and Morty",
    "Shazam!",
    "Captain America",
    "Daredevil",
    "Doctor Strange",
    "Fables",
    "Thundercats",
    "Absolute Green Lantern",
    "Absolute Superman",
    "Batgirl",
    "Birds of Prey",
    "The Immortal Thor",
    "Furrlough",
    "Tomorrow Girl",
    "Absolute Wonder Woman",
    "DC Connect",
    "Green Arrow",
    "Justice League Unlimited",
    "Superman",
    "Gunslinger Spawn",
    "Spider-Boy",
    "The Incredible Hulk",
    "Uncanny X-Men",
    "Grim",
    "JSA",
    "All-New Venom",
    "Hellverine",
    "The Avengers",
    "Ultimate Wolverine",
    "X-Men",
    "Adventure Time",
    "Harley Quinn",
    "Aquaman",
    "Green Lantern Corps",
    "Supergirl",
    "Absolute Flash",
    "The New Gods",
    "Titans",
    "Zatanna",
    "G.I. Joe",
    "Ultimate Black Panther",
    "MAD Magazine",
    "Alice Forever After",
    "Absolute Green Arrow",
    "Archie x End of Life",
    "Batman / Superman: World's Finest",
    "Deathstroke: The Terminator",
    "Lobo",
    "New Titans",
    "Superman Unlimited",
    "Monster High: Boomuda Triangle",
    "Zorro",
    "The Darkness",
    "Alias: Red Band",
    "Sai: Dimensional Rivals",
    "Sorcerer Supreme",
    "Ultimate Impact: Reborn",
];

async function backfill() {
    const batchSize = 25;
    for (let i = 0; i < SERIES_TO_BACKFILL.length; i += batchSize) {
        const batch = SERIES_TO_BACKFILL.slice(i, i + batchSize);
        await ddb.batchWrite({
            RequestItems: {
                [TABLE_NAME]: batch.map(seriesName => ({
                    PutRequest: { Item: { seriesName } }
                }))
            }
        });
        console.log(`Backfilled ${Math.min(i + batchSize, SERIES_TO_BACKFILL.length)} / ${SERIES_TO_BACKFILL.length}`);
    }
    console.log('Done!');
}

backfill().catch(console.error);
